services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: dvdrental
      POSTGRES_USER: postgres
    ports:
      - "5433:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - "./dvdrental.tar:/docker-entrypoint-initdb.d/dvdrental.tar" # Mount the tar file inside the container
      - "./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh" # Mount initialization script

volumes:
  postgres-data:
