services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    env_file:
      - .env
    volumes:
      - './src/:/home/node/app/src:ro'
      - './node_modules/:/home/node/app/node_modules'
      - './package.json:/home/node/app/package.json'
