services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - './node_modules:/home/node/app/node_modules'
      - '.:/home/node/app'
    networks:
      - my-net
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - winston-demo-mongo-data:/data/db
    networks:
      - my-net

networks:
  my-net:

volumes:
  winston-demo-mongo-data: