@URL=http://localhost:4000

### Ping Server
GET {{URL}}

### send email
POST {{URL}}/send-email
Content-Type: application/json

{
    "to": "user@example.com",
    "subject": "Hello",
    "body": "Hello, this is a test email",
    "format": "text"
}

### send email
POST {{URL}}/send-email
Content-Type: application/json

{
    "to": "user@example.com",
    "subject": "Hello",
    "body": "Hello, this is a test email",
    "format": "html"
}