services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '4000:4000'
    env_file:
      - .env
    volumes:
      - './src:/home/node/app/src/:ro'
      - './package.json:/home/node/app/package.json'
      - './node_modules:/home/node/app/node_modules'
