# Base URL for the API
@baseUrl = http://localhost:3000

#### GET Request to the root endpoint
GET {{baseUrl}}/


#### POST Request to create new tag
POST {{baseUrl}}/tags
Content-Type: application/json

{
    "tag": "Node.js"
}

#### GET Request to get all tags
GET {{baseUrl}}/tags


#### GET Request to get tag by prefix
GET {{baseUrl}}/tags?prefix=No